config/routes.rb
# encoding: utf-8

JobTest5::Application.routes.draw do
	match "auth/:action", controller: :auth
	match "rss", to: "news#rss"

	resources :news, :questions, :comments, only: [:index, :create, :show] do
		resources :votes, only: [:create]
		resources :comments, only: [:index, :create, :show]
	end

	root to: "news#index"
end

app/models/Comment.rb
# encoding: utf-8

class Comment < ActiveRecord::Base
	include ::Common

	belongs_to :user
	has_many :comments, as: :commentable, order: "updated_at DESC"
	has_many :votes, as: :voteable, order: "updated_at DESC"

	validates :content, presence: true
	before_save :parse_content

	def as_json(options = {})
		rv = {
			id: self.id,
			content: self.parsed_content,
			user: self.user.as_json,
			created_at: self.created_at.strftime("%F %T"),
			comments: self.comments.as_json,
			votes: Vote.count_for(self)
		}
	end
end

app/models/News.rb
# encoding: utf-8

class News < ActiveRecord::Base
	include ::Common

	belongs_to :user
	has_many :comments, as: :commentable, order: "updated_at DESC"
	has_many :votes, as: :voteable, order: "updated_at DESC"

	validates :title, :url, presence: true

	def as_json(options = {})
		rv = {
			id: self.id,
			title: self.title,
			url: self.url,
			host: self.host,
			user: self.user.as_json,
			created_at: self.created_at.strftime("%F %T"),
			votes: Vote.count_for(self),
			comments: self.comments.as_json
		}
	end

	def host
		URI.parse(self.url).host
	end
end

app/models/Question.rb
# encoding: utf-8

class Question < ActiveRecord::Base
	include ::Common

	belongs_to :user
	has_many :comments, as: :commentable, order: "updated_at DESC"
	has_many :votes, as: :voteable, order: "updated_at DESC"

	validates :title, :content, presence: true
	before_save :parse_content

	def as_json(options = {})
		rv = {
			id: self.id,
			title: self.title,
			content: self.parsed_content,
			user: self.user.as_json,
			created_at: self.created_at.strftime("%F %T"),
			votes: Vote.count_for(self),
			comments: self.comments.as_json
		}
	end
end

app/models/User.rb
# encoding: utf-8

class User < ActiveRecord::Base
	has_many :news
	has_many :questions
	has_many :votes
	has_many :comments

	validates :username, uniqueness: true

	def self.encrypt(plain)
		Digest::SHA2.hexdigest(plain)
	end

	def password=(value)
		write_attribute(:password, self.class.encrypt(value))
	end

	def tokenize
		[self.id, self.class.encrypt(self.username), self.password].join("")
	end

	def as_json(options = {})
		{
			id: self.id,
			username: self.username,
			created_at: self.created_at.strftime("%F %T")
		}
	end
end

app/models/Vote.rb
# encoding: utf-8

class Vote < ActiveRecord::Base
	belongs_to :user

	scope :ups, conditions: {positive: true}
	scope :downs, conditions: {positive: false}

	def self.count_for(obj)
		{ups: obj.votes.ups.count, downs: obj.votes.downs.count}
	end
end

app/controllers/application_controller.rb
# encoding: utf-8

class ApplicationController < ActionController::Base
	protect_from_forgery

	before_filter :authenticate
	before_filter :setup

	def authenticate
		@current_user = nil
		token = cookies["auth-token"].ensure_string

		if token =~ /^((?<id>\d+)(.{128}))$/ then
			id = $~["id"].to_integer

			begin
				@current_user = User.find(id)
				@current_user = nil if @current_user.tokenize != token
			rescue ActiveRecord::RecordNotFound
			end

			cookies.delete("auth-token") if !@current_user
		end
	end

	def check_authentication
		self.authenticate
		render json: {message: "You must be authenticated to perform this request."}, status: 401 if !@current_user
	end

	def lookup_parent
		@parent_class = catch(:klass) do
			throw(:klass, News) if params[:news_id].present?
			throw(:klass, Question) if params[:question_id].present?
			throw(:klass, Comment) if params[:comment_id].present?
			redirect_to :root
		end

		begin
			@parent = @parent_class.find(params[(@parent_class.to_s.parameterize + "_id").to_sym])
		rescue ActiveRecord::RecordNotFound
			redirect_to :root
		end
	end

	def setup

	end
end

app/controllers/auth_controller.rb
# encoding: utf-8

class AuthController < ApplicationController
	skip_before_filter :authenticate, only: :login

	def login
		begin
			user = params[:user]
			user[:password] = User.encrypt(user[:password])

			valid_user = User.where(user).first

			if valid_user then
				cookies["auth-token"] = {value: valid_user.tokenize, path: "/", expire: 1.hours.from_now}
				render json: {message: "OK"}
			else
				render json: {message: "Invalid username or password."}, status: 401
			end
		rescue Exception => e
			render json: {message: e.to_s}, status: 500
		end
	end

	def logout
		cookies.delete("auth-token")
		redirect_to :root
	end

	def register
		begin
			user = params[:user]
			user.delete(:confirm_password)

			valid_user = User.create!(user)
			cookies["auth-token"] = {value: valid_user.tokenize, path: "/", expire: 1.hours.from_now}
			render json: {message: "OK"}
		rescue ActiveRecord::RecordInvalid => e
			render json: {message: "Username has already be taken."}, status: 403
		rescue Exception => e
			render json: {message: "Error occurred: " + e.to_s}, status: 500
		end
	end
end

app/controllers/comments_controller.rb
# encoding: utf-8

class CommentsController < NewsController
	before_filter :lookup_parent, :only => [:create]

	def setup
		@model_class = Comment
	end

	def create
		begin
			record = @model_class.new(params[:comment])
			record.user = @current_user
			raise ActiveRecord::RecordInvalid.new(record) if !record.valid?

			@parent.comments << record
			@parent.save!

			render json: {message: "OK", data: record.as_json}
		rescue Exception => e
			render json: {message: "Error occurred: " + e.to_s}, status: 500
		end
	end
end

app/controllers/news_controller.rb
# encoding: utf-8

class NewsController < ApplicationController
	before_filter :check_authentication, except: [:index, :show, :rss]

	def setup
		@model_class = News
	end

	def index
		@paginator = {
			page: [1, params[:page].to_integer].max,
			count: [@model_class.per_page, params[:count].to_integer].max
		}
		@paginator[:offset] = (@paginator[:page] - 1) * @paginator[:count]

		if request.xhr? then
			records = @model_class.fetch(@paginator, true)
			render json: records
		else
			@records = @model_class.fetch(@paginator, true)
		end
	end

	def create
		begin
			record = @model_class.new(params[@model_class.to_s.parameterize.to_sym])
			record.user = @current_user
			record.save!

			render json: {message: "OK"}
		rescue Exception => e
			render json: {message: "Error occurred: " + e.to_s}, status: 500
		end
	end

	def show
		begin
			@record = @model_class.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_to action: :index
		end
	end

	def rss
		@records = @model_class.fetch({}, false, false)
		render :rss => @records
	end
end

app/controllers/questions_controller.rb
# encoding: utf-8

class QuestionsController < NewsController
	def setup
		@model_class = Question
	end
end

app/controllers/votes_controller.rb
# encoding: utf-8

class VotesController < ApplicationController
	before_filter :check_authentication
	before_filter :lookup_parent

	def create
		begin
			if @parent.votes.where(user_id: @current_user.id).count == 0 then
				@parent.votes << Vote.new({user: @current_user, positive: params[:positive].to_boolean})
				@parent.save!
			end

			if request.xhr? then
				render json: {message: "OK", data: Vote.count_for(@parent) }
			else
				redirect_to :root
			end
		rescue Exception => e
			render json: {message: "Error occurred: " + e.to_s}, status: 500
		end
	end
end

app/views/comments/index.html.erb
<% content_for(:additional_js) do %>
	<script type="text/javascript">
		Environment.instance().on("loaded", function(){
			Environment.instance().set("comments-skip-replies", true);
			Environment.instance().set("paginator-url-comments", "<%= comments_path(:page => "__page__") %>");
			comments_list = new CommentsList(<%= @records.to_json.html_safe %>);
		});
	</script>
<% end %>

<%= content_for(:title, "Comments") %>

<section id="comments-list">
	<div id="comments-container" class="comments-container"></div>
	<div id="comments-paginator" class="comments-paginator"></div>
</section>

<%= render :partial => "partials/comments" %>

app/views/comments/show.html.erb
<% content_for(:additional_js) do %>
	<script type="text/javascript">
		Environment.instance().on("loaded", function(){
			comment = new CommentView({model: new Comment(<%= @record.to_json.html_safe %>)}, true);
			comment.renderTo($("#root"), true);
		});
	</script>
<% end %>

<%= content_for(:title, "Discussion on comment ##{@record.id}") %>

<%= render :partial => "partials/comments" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	   <title><%= yield(:title) %> &laquo; Job Test 5</title>
	   <%= stylesheet_link_tag "application", media: "all" %>
	   <%= javascript_include_tag "application" %>

	   <%= yield :additional_css %>

		<script type="text/javascript">
			Environment.instance().set("params", <%= params.to_json.html_safe %>);
			Environment.instance().set("user", <%= (@current_user ? @current_user.username : nil).to_json.html_safe %>);
		</script>
	   <%= javascript_include_tag params[:controller] %>
		<%= yield :additional_js %>

	   <%= yield :templates %>

	   <%= csrf_meta_tags %>
	</head>
	<body class="<%= @current_user ? "logged" : "" %>">
		<div class="navbar navbar-fixed-top">
		   <div class="navbar-inner">
		      <header class="container">
		         <%= link_to(:root, class: :brand) do %><i class="icon-bookmark"></i> Hacker News<% end %>

		         <ul class="nav">
		            <li><%= link_to({controller: :news, action: :index}, {id: "news-refresh"}) do %><i class="icon-refresh"></i> News<% end %></li>
		            <li><%= link_to(questions_path, {id: "questions-refresh"}) do %><i class="icon-question-sign"></i> Questions<% end %></li>
		            <li><%= link_to(comments_path, {id: "comments-refresh"}) do %><i class="icon-comments"></i> Comments<% end %></li>
		            <li><%= link_to({controller: :news, action: :rss}) do %><i class="icon-star"></i> RSS Feed<% end %></li>
		         </ul>

		         <ul class="nav pull-right">
		            <% if !@current_user then %>
		               <li><%= link_to("#dialogs-auth-login", "data-toggle" => "modal") do %><i class="icon-signin"></i> Login<% end %></li>
		               <li><%= link_to("#dialogs-auth-register", "data-toggle" => "modal") do %><i class="icon-user"></i> Register<% end %></li>
		            <% else %>
				         <% if controller.class == NewsController then %>
		                  <li><%= link_to("#dialogs-submit-news", "data-toggle" => "modal") do %><i class="icon-align-left"></i> Submit news<% end %></li>
					      <% elsif controller.class == QuestionsController then %>
		                  <li><%= link_to("#dialogs-submit-question", "data-toggle" => "modal") do %><i class="icon-question-sign"></i> Submit question<% end %></li>
						   <% end %>
		               <li><%= link_to({controller: :auth, action: :logout}, id: "auth-logout") do %><i class="icon-signout"></i> Logout (<%= @current_user.username %>)<% end %></li>
		            <% end %>
		         </ul>
		      </header>
		   </div>
		</div>

		<div class="container">
			<h1><%= yield :title %></h1>

		   <div id="alerts"></div>
			<div id="root"></div>
		   <%= yield %>

		   <footer class="footer">
		      <p>&copy; 2012 and above <a class="external" href="http://cowtech.it">Paolo Insogna</a>, released under the <a class="external" href="http://www.opensource.org/licenses/mit-license.php">MIT License</a>. Obviously inspired to <a class="external" href="http://news.ycombinator.com/">Y Hacker News</a>.</p>
		   </footer>
		</div>

		<div class="dialogs">
			<%= render partial: "partials/dialogs" %>
		</div>

		<a class="forker" href="https://github.com/ShogunCow/cowtech-job-test-4"><img src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png" alt="Fork me on GitHub"/></a>
	</body>
</html>

app/views/news/index.html.erb
<% content_for(:additional_js) do %>
	<script type="text/javascript">
		Environment.instance().on("loaded", function(){
			Environment.instance().set("paginator-url-news", "<%= news_index_path(:page => "__page__") %>");
			news_list = new NewsList(<%= @records.to_json.html_safe %>);
		});
	</script>
<% end %>

<%= content_for(:title, "News") %>

<section id="news-list">
	<div id="news-container" class="news-container"></div>
	<div id="news-paginator" class="news-paginator"></div>
</section>

<%= render :partial => "partials/news" %>

app/views/news/show.html.erb
<% content_for(:additional_js) do %>
	<script type="text/javascript">
		Environment.instance().on("loaded", function(){
			news = new NewsView({model: new News(<%= @record.to_json().html_safe %>)});
			news.renderTo($("#root"), true);
		});
	</script>
<% end %>

<%= content_for(:title, "Discussion on news ##{@record.id}: #{@record.title}") %>

<%= render :partial => "partials/news" %>
<%= render :partial => "partials/comments" %>

app/views/partials/_comments.html.erb
<% content_for(:additional_js) do %>
   <script type="text/javascript">
	   Environment.instance().set("urls-comments", {
		   "news": "<%= news_comments_path("__id__") %>",
		   "questions": "<%= question_comments_path("__id__") %>",
		   "comments": "<%= comment_comments_path("__id__") %>"
	   });
   </script>
<% end %>

<% content_for(:templates) do %>
   <script id="templates-comment-multi" type="text/template">
      <div class="alert">
         <div class="row-fluid">
            <div class="span6">
               <h4 class="metadata"><b>{{user.username}}</b> said on <b>{{created_at}}</b>:</h4>
            </div>

            <div class="span6 align-right">
               <%= link_to("<i class=\"icon-comment\"></i> Reply".html_safe, comment_path("__id__")) %>
               &nbsp;
               <%= link_to(comment_votes_path("__id__", {positive: true}), {class: :vote, remote: true, method: :post, "data-type" => "json"}) do %><span class="votes-ups">{{votes.ups}}</span> <i class="icon-thumbs-up"></i><% end %>
               <%= link_to(comment_votes_path("__id__", {positive: false}), {class: :vote, remote: true, method: :post, "data-type" => "json"}) do %><span class="votes-downs">{{votes.downs}}</span> <i class="icon-thumbs-down"></i><% end %>
            </div>
         </div>

         <div class="comment-content">{{content}}</div>
      </div>
   </script>

   <script id="templates-comment-single" type="text/template">
      <div class="alert">
         <div class="row-fluid">
            <div class="span6">
               <h3 class="metadata"><b>{{user.username}}</b> said on <b>{{created_at}}</b>:</h3>
            </div>

            <div class="span6 align-right">
               <%= link_to(comment_votes_path("__id__", {positive: true}), {class: :vote, remote: true, method: :post, "data-type" => "json"}) do %><span class="votes-ups">{{votes.ups}}</span> <i class="icon-thumbs-up"></i><% end %>
               <%= link_to(comment_votes_path("__id__", {positive: false}), {class: :vote, remote: true, method: :post, "data-type" => "json"}) do %><span class="votes-downs">{{votes.downs}}</span> <i class="icon-thumbs-down"></i><% end %>
					<br/>
               <span><i class="icon-comments"></i> <span class="comments-count">{{CommentsList.label_for(comments.length, "No comments")}}</span></span>
            </div>
         </div>

         <div class="comment-content">{{content}}</div>
      </div>
   </script>

   <script id="templates-comment-form" type="text/template">
      <%= simple_form_for(Comment.new, {url: "__url__", html: {id: "comment-edit", class: "container-fluid", remote: true}}) do |f| %>
         <%= f.input :content, as: :text, label: false, input_html: {class: "span12"} %>

         <div class="row-fluid">
            <div class="span6"><span class="hint">You can use <b>Markdown</b> syntax.</span></div>
            <div class="span6 align-right"><button type="submit" class="btn btn-primary"><i class="icon-comment"></i> <span>{{label}}</span></button></div>
         </div>
      <% end %>
   </script>
<% end %>

app/views/partials/_dialogs.html.erb
<div class="modal" id="dialogs-auth-login">
	<%= simple_form_for(User.new, url: url_for(controller: :auth, action: "login"), html: {class: "form-horizontal", remote: true, "data-type" => "json"}) do |f| %>
		<div class="modal-header">
			<a class="close" data-dismiss="modal"><i class="icon-remove"></i></a>
			<h3>Login</h3>
		</div>
	   <div class="modal-body">
			<%= f.input :username, label: "Username:", input_html: {class: "span4"} %>
		   <%= f.input :password, label: "Password:", input_html: {class: "span4"} %>
		</div>
	   <div class="modal-footer form-actions">
		   <button type="submit" class="btn btn-primary"><i class="icon-signin"></i> <span>Login</span></button>
		</div>
	<% end %>
</div>

<div class="modal" id="dialogs-auth-register">
	<%= simple_form_for(User.new, url: url_for(controller: :auth, action: "register"), html: {class: "form-horizontal", remote: true, "data-type" => "json"}) do |f| %>
		<div class="modal-header">
			<a class="close" data-dismiss="modal"><i class="icon-remove"></i></a>
			<h3>Register</h3>
		</div>
	   <div class="modal-body">
			<%= f.input :username, label: "Username:", input_html: {class: "span4"} %>
		   <%= f.input :password, label: "Password:", input_html: {class: "span4"} %>
	      <%= f.input :confirm_password, label: "Confirm password:", input_html: {class: "span4"} %>
		</div>
	   <div class="modal-footer form-actions">
		   <button type="submit" class="btn btn-primary"><i class="icon-user"></i> <span>Register</span></button>
		</div>
	<% end %>
</div>

<div class="modal" id="dialogs-submit-news">
	<%= simple_form_for(News.new, html: {class: "form-horizontal", remote: true, "data-type" => "json"}) do |f| %>
		<div class="modal-header">
			<a class="close" data-dismiss="modal"><i class="icon-remove"></i></a>
			<h3>Submit news</h3>
		</div>
	   <div class="modal-body">
			<%= f.input :title, label: "Title:", input_html: {class: "span4"} %>
		   <%= f.input :url, label: "URL:", input_html: {class: "span4"} %>
		</div>
	   <div class="modal-footer form-actions">
		   <button type="submit" class="btn btn-primary"><i class="icon-ok"></i> <span>Submit</span></button>
		</div>
	<% end %>
</div>

<div class="modal" id="dialogs-submit-question">
	<%= simple_form_for(Question.new, html: {class: "form-horizontal", remote: true, "data-type" => "json"}) do |f| %>
		<div class="modal-header">
			<a class="close" data-dismiss="modal"><i class="icon-remove"></i></a>
			<h3>Submit question</h3>
		</div>
	   <div class="modal-body">
			<%= f.input :title, label: "Title:", input_html: {class: "span4"} %>
	      <%= f.input :content, as: :text, label: "Description:", input_html: {class: "span4"}, :hint => "You can use <b>Markdown</b> syntax.".html_safe %>
		</div>
	   <div class="modal-footer form-actions">
		   <button type="submit" class="btn btn-primary"><i class="icon-ok"></i> <span>Ask</span></button>
		</div>
	<% end %>
</div>

app/views/partials/_news.html.erb
<% content_for(:templates) do %>
	<script type="text/template" id="templates-news-multi">
	   <div class="span6">
	      <h4>
	         <span class="number">{{index}}</span>
	         <a class="external" href="{{url}}">{{title}}</a>
	         <span class="host">({{host}})</span>
	      </h4>
	      <p class="metadata">
	         Posted by <b>{{user.username}}</b> on <b>{{created_at}}</b>
	      </p>
	   </div>

	   <div class="span6 align-right">
	      <%= link_to(news_votes_path("__id__", {positive: true}), {class: :vote, remote: true, method: :post, "data-type" => "json"}) do %><span class="votes-ups">{{votes.ups}}</span> <i class="icon-thumbs-up"></i><% end %>
	      <%= link_to(news_votes_path("__id__", {positive: false}), {class: :vote, remote: true, method: :post, "data-type" => "json"}) do %><span class="votes-downs">{{votes.downs}}</span> <i class="icon-thumbs-down"></i><% end %>
	      <br/>
	      <%= link_to(news_path("__id__"), {class: "pull-right"}) do %><i class="icon-comments"></i> {{CommentsList.label_for(comments.length, "Discuss")}}<% end %>
	   </div>
	</script>

	<script type="text/template" id="templates-news-single">
	   <div class="row-fluid">
	      <div class="span6">
	         <h3>
	            <a class="external" href="{{url}}">{{title}}</a>
	            <span class="host">({{host}})</span>
	         </h3>
	         <p class="metadata">
	            Posted by <b>{{user.username}}</b> on <b>{{created_at}}</b>
	         </p>
	      </div>

	      <div class="span6 align-right">
	         <%= link_to(news_votes_path("__id__", {positive: true}), {class: :vote, remote: true, method: :post, "data-type" => "json"}) do %><span class="votes-ups">{{votes.ups}}</span> <i class="icon-thumbs-up"></i><% end %>
	         <%= link_to(news_votes_path("__id__", {positive: false}), {class: :vote, remote: true, method: :post, "data-type" => "json"}) do %><span class="votes-downs">{{votes.downs}}</span> <i class="icon-thumbs-down"></i><% end %>
	         <br/>
	         <span><i class="icon-comments"></i> <span class="comments-count">{{CommentsList.label_for(comments.length, "No comments")}}</span></span>
	      </div>
	   </div>
	</script>
<% end %>

app/views/partials/_questions.html.erb
<% content_for(:templates) do %>
	<script type="text/template" id="templates-question-multi">
		<div class="alert">
			<div class="row-fluid">
			   <div class="span6">
			      <h4><%= link_to("__title__", question_path("__id__"), {class: :external}) %></h4>
			      <p class="metadata">
			         Posted by <b>{{user.username}}</b> on <b>{{created_at}}</b>
			      </p>
			   </div>

			   <div class="span6 align-right">
			      <%= link_to(question_votes_path("__id__", {positive: true}), {class: :vote, remote: true, method: :post, "data-type" => "json"}) do %><span class="votes-ups">{{votes.ups}}</span> <i class="icon-thumbs-up"></i><% end %>
			      <%= link_to(question_votes_path("__id__", {positive: false}), {class: :vote, remote: true, method: :post, "data-type" => "json"}) do %><span class="votes-downs">{{votes.downs}}</span> <i class="icon-thumbs-down"></i><% end %>
			      <br/>
			      <%= link_to(question_path("__id__"), {class: "pull-right"}) do %><i class="icon-comments"></i> {{CommentsList.label_for(comments.length, "Reply")}}<% end %>
			   </div>
			</div>

		   <div class="question-content">{{content}}</div>
		</div>
	</script>

	<script type="text/template" id="templates-question-single">
	   <div class="alert">
	      <div class="row-fluid">
		      <div class="span6">
		         <h3>{{title}}</h3>
		         <p class="metadata">
		            Posted by <b>{{user.username}}</b> on <b>{{created_at}}</b>
		         </p>
		      </div>

		      <div class="span6 align-right">
		         <%= link_to(question_votes_path("__id__", {positive: true}), {class: :vote, remote: true, method: :post, "data-type" => "json"}) do %><span class="votes-ups">{{votes.ups}}</span> <i class="icon-thumbs-up"></i><% end %>
		         <%= link_to(question_votes_path("__id__", {positive: false}), {class: :vote, remote: true, method: :post, "data-type" => "json"}) do %><span class="votes-downs">{{votes.downs}}</span> <i class="icon-thumbs-down"></i><% end %>
		         <br/>
		         <span><i class="icon-comments"></i> <span class="comments-count">{{CommentsList.label_for(comments.length, "No replies")}}</span></span>
		      </div>
		   </div>

		   <div class="question-content">{{content}}</div>
		</div>
	</script>
<% end %>

app/views/questions/index.html.erb
<% content_for(:additional_js) do %>
	<script type="text/javascript">
		Environment.instance().on("loaded", function(){
			Environment.instance().set("paginator-url-questions", "<%= questions_path(:page => "__page__") %>");
			questions_list = new QuestionsList(<%= @records.to_json.html_safe %>);
		});
	</script>
<% end %>

<%= content_for(:title, "Questions") %>

<section id="questions-list">
	<div id="questions-container" class="questions-container"></div>
	<div id="questions-paginator" class="questions-paginator"></div>
</section>

<%= render :partial => "partials/questions" %>

app/views/questions/show.html.erb
<% content_for(:additional_js) do %>
	<script type="text/javascript">
		Environment.instance().on("loaded", function(){
			news = new QuestionView({model: new Question(<%= @record.to_json().html_safe %>)});
			news.renderTo($("#root"), true);
		});
	</script>
<% end %>

<%= content_for(:title, "Question ##{@record.id}: #{@record.title}") %>

<%= render :partial => "partials/questions" %>
<%= render :partial => "partials/comments" %>